
services:

  db:
    build: ./_build/db

    networks:
      - back

    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - main_db:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: ${DATABASE_DB:-place_db}
      POSTGRES_USER: ${DATABASE_USERNAME:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?required}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DATABASE_DB:-place_db}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  cache:
    build: ./_build/redis

    command: 'redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'

    networks:
      - back

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - cache:/data

    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:?required}

  back:
    depends_on:
      cache:
        condition: service_started
      db:
        condition: service_healthy

    networks:
      - back

    volumes:
      - /etc/localtime:/etc/localtime:ro

    environment:
      CANVAS_X: ${CANVAS_X:-200}
      CANVAS_Y: ${CANVAS_Y:-200}
      
      PIXEL_BUFFER_SIZE: ${PIXEL_BUFFER_SIZE:-10}
      PIXEL_MINUTE_TIMER: ${PIXEL_MINUTE_TIMER:-60}

      UTC_TIME_START: ${UTC_TIME_START-}
      UTC_TIME_END: ${UTC_TIME_END-}

      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DATABASE_DB:-place_db}
      POSTGRES_USER: ${DATABASE_USERNAME:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?required}
  
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:?required}

      REDIS_SPAN_SECONDS: ${REDIS_SPAN_SECONDS:-3600}
      REDIS_MIN_SECONDS: ${REDIS_MIN_SECONDS:-0}

      JWT_SECRET: ${JWT_SECRET:?required}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-60}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN:-7200}

      ENABLE_GUEST_LOGIN: ${ENABLE_GUEST_LOGIN-false}

      ENABLE_OAUTH2_LOGIN: ${ENABLE_OAUTH2_LOGIN-false}
      OAUTH2_UID: ${OAUTH2_UID-}
      OAUTH2_SECRET: ${OAUTH2_SECRET-}

      OAUTH2_AUTHORIZE_URL: ${OAUTH2_AUTHORIZE_URL-}
      OAUTH2_TOKEN_URL: ${OAUTH2_TOKEN_URL-}
      OAUTH2_CALLBACK_URL: ${OAUTH2_CALLBACK_URL-}
      OAUTH2_INFO_URL: ${OAUTH2_INFO_URL-}

      OAUTH2_ID_FIELD: ${OAUTH2_ID_FIELD-}
      OAUTH2_USERNAME_FIELD: ${OAUTH2_USERNAME_FIELD-}
      OAUTH2_EMAIL_FIELD: ${OAUTH2_EMAIL_FIELD-}


    working_dir: /app

  nginx:
    depends_on:
      - back

    networks:
      - back

    volumes:
      - /etc/localtime:/etc/localtime:ro


networks:
  back:

volumes:
  main_db:
  cache:


