version: "3.7"


services:

  db:
    build: ./_build/db

    networks:
      - back

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - main_db:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${DATABASE_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  cache:
    # image: redis:6.2-alpine
    build: ./_build/redis

    command: 'redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'

    networks:
      - back

    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - cache:/data

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  back:
    build: ./_build/node

    depends_on:
      cache:
        condition: service_started
      db:
        condition: service_healthy

    networks:
      - back

    volumes:
      - /etc/localtime:/etc/localtime:ro

    environment:
      CANVAS_X: ${CANVAS_X}
      CANVAS_Y: ${CANVAS_Y}

      UTC_TIME_START: ${UTC_TIME_START}
      UTC_TIME_END: ${UTC_TIME_END}

      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      REDIS_SPAN_SECONDS: ${REDIS_SPAN_SECONDS}
      REDIS_MIN_SECONDS: ${REDIS_MIN_SECONDS}

      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      
      PIXEL_BUFFER_SIZE: ${PIXEL_BUFFER_SIZE}
      PIXEL_MINUTE_TIMER: ${PIXEL_MINUTE_TIMER}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}

      API_UID: ${API_UID}
      API_SECRET: ${API_SECRET}
      API_CALLBACK: ${API_CALLBACK}

    working_dir: /app




  nginx:
    build: 
      context: .
      dockerfile: ./_build/nginx/Dockerfile

    depends_on:
      - front
      - back

    networks:
      - front
      - back

    ports:
     - "7979:80"

    volumes:
      - /etc/localtime:/etc/localtime:ro


networks:
  front:
  back:

volumes:
  main_db:
  cache:


