version: "3.7"


services:

  adminer:
    image: adminer

    depends_on:
      - db

    ports:
      - "8082:8080"

    networks:
      - back

  back:
    ports:
      - "8081:8080"

    volumes:
      - ./back:/app

  front:
    ports:
     - "8080:5173"

    volumes:
      - ./front:/app
