
services:

  adminer:
    image: adminer

    depends_on:
      - db

    networks:
      - back

    ports:
      - "8082:8080"


  back:
    build: ./_build/node
    
    ports:
      - "8081:8080"

    volumes:
      - ./back:/app

    environment:
      NODE_ENV: DEV

  front:
    build: ./_build/react

    networks:
      - front

    ports:
     - "8080:5173"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./front:/app

    environment:
      VITE_NODE_ENV: DEV
  
      VITE_CANVAS_MIN_X: ${CANVAS_MIN_X:-0}
      VITE_CANVAS_MIN_Y: ${CANVAS_MIN_Y:-0}
      VITE_CANVAS_MAX_X: ${CANVAS_MAX_X:-200}
      VITE_CANVAS_MAX_Y: ${CANVAS_MAX_Y:-200}

      VITE_ENABLE_GUEST_LOGIN: ${ENABLE_GUEST_LOGIN-false}
      VITE_ENABLE_LOCAL_LOGIN: ${ENABLE_LOCAL_LOGIN-false}
      VITE_ENABLE_LOCAL_CREATE: ${ENABLE_LOCAL_CREATE-false}
      VITE_ENABLE_OAUTH2_LOGIN: ${ENABLE_OAUTH2_LOGIN-false}

      VITE_OAUTH2_DISPLAY_NAME: ${OAUTH2_DISPLAY_NAME-}
    
    working_dir: /app


  nginx:
    build: 
      context: .
      dockerfile: ./_build/nginx/Dockerfile

    depends_on:
      - front
      - back

    networks:
      - front
      - back

    ports:
     - "7979:80"
     
networks:
  front:
