
services:

  db:
    restart: "always"


  cache:
    restart: "always"


  back:
    build: 
      context: .
      dockerfile: ./_build/node/Dockerfile-prod

    restart: "always"

    environment:
      NODE_ENV: PROD


  nginx:
    build: 
      context: .
      dockerfile: ./_build/nginx/Dockerfile-prod
      args:
        VITE_NODE_ENV: PROD
        VITE_CANVAS_MIN_X: ${CANVAS_MIN_X:-0}
        VITE_CANVAS_MIN_Y: ${CANVAS_MIN_Y:-0}
        VITE_CANVAS_MAX_X: ${CANVAS_MAX_X:-200}
        VITE_CANVAS_MAX_Y: ${CANVAS_MAX_Y:-200}

        VITE_ENABLE_GUEST_LOGIN: ${ENABLE_GUEST_LOGIN-}
        VITE_ENABLE_LOCAL_LOGIN: ${ENABLE_LOCAL_LOGIN-}
        VITE_ENABLE_LOCAL_CREATE: ${ENABLE_LOCAL_CREATE-}
        VITE_ENABLE_OAUTH2_LOGIN: ${ENABLE_OAUTH2_LOGIN-}

        VITE_OAUTH2_DISPLAY_NAME: ${OAUTH2_DISPLAY_NAME-}

    restart: "always"

    ports:
     - "${PROD_PORT:-8403}:80"
     #- "${PROD_PORT:-8403}:443"

    #volumes:
    # - "/etc/cert.crt:/etc/certs/cert.crt:ro"
    # - "/etc/cert.key:/etc/certs/cert.key:ro"