version: "3.7"


services:

  adminer:
    image: adminer

    depends_on:
      - db

    networks:
      - back

    ports:
      - "8082:8080"


  back:
    ports:
      - "8081:8080"

    volumes:
      - ./back:/app

    environment:
      NODE_ENV: DEV

  front:
    build: ./_build/react

    networks:
      - front

    ports:
     - "8080:5173"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./front:/app

    environment:
      # VITE_NODE_ENV: DEV
      VITE_CANVAS_X: ${CANVAS_X}
      VITE_CANVAS_Y: ${CANVAS_Y}
    
    working_dir: /app
