FROM node:lts-alpine3.20

WORKDIR /app

COPY back .

RUN apk add python3 pixman-dev cairo-dev pango-dev make g++
RUN yarn install --production
RUN yarn add typescript -g
RUN yarn build

CMD ["node", "dist/main.js"]