FROM node:18-alpine AS build
ARG VITE_NODE_ENV

ARG VITE_CANVAS_MIN_X
ARG VITE_CANVAS_MIN_Y
ARG VITE_CANVAS_MAX_X
ARG VITE_CANVAS_MAX_Y

ARG VITE_ENABLE_GUEST_LOGIN
ARG VITE_ENABLE_OAUTH2_LOGIN

ARG VITE_OAUTH2_DISPLAY_NAME

WORKDIR /app

COPY front .

RUN yarn install --production 
RUN yarn add typescript -g
RUN yarn build


FROM nginx

WORKDIR /usr/share/nginx/html

COPY _build/nginx/local-prod.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html

